export const productModel = [
  { name: 'productCode', label: 'Product Code', required: true },
  { name: 'productName', label: 'Product Name', required: true },
  { name: 'shortDescription', label: 'Short Description' },
  { name: 'longDescription', label: 'Long Description', type: 'textarea' },
  { name: 'categoryId', label: 'Category', type: 'dropdown', endpoint: '/api/categories/dropdown' },
  { name: 'uomId', label: 'UOM', type: 'dropdown', endpoint: '/api/uoms/dropdown' },
  { name: 'barcode', label: 'Barcode' },
  { name: 'manufacturer', label: 'Manufacturer' },
  { name: 'brand', label: 'Brand' },
  { name: 'countryOfOrigin', label: 'Country Of Origin' },
  { name: 'weight', label: 'Weight', type: 'number' },
  { name: 'length', label: 'Length', type: 'number' },
  { name: 'width', label: 'Width', type: 'number' },
  { name: 'height', label: 'Height', type: 'number' },
  { name: 'volume', label: 'Volume', type: 'number' },
  { name: 'shelfLifeDays', label: 'Shelf Life (Days)', type: 'number' },
  { name: 'expiryRequired', label: 'Expiry Required', type: 'checkbox' },
  { name: 'serialTracking', label: 'Serial Tracking', type: 'checkbox' },
  { name: 'lotTracking', label: 'Lot Tracking', type: 'checkbox' },
  { name: 'hazardous', label: 'Hazardous', type: 'checkbox' },
  { name: 'temperatureType', label: 'Temperature Type', type: 'dropdown', options: ['AMBIENT', 'DRY', 'REFRIGERATED', 'FROZEN', 'CONTROLLED'] },
  { name: 'imageUrl', label: 'Image URL' }
];
