export const locationModel = [
  { name: 'locationCode', label: 'Location Code', required: true },
  { name: 'locationName', label: 'Location Name', required: true },
  { name: 'locationType', label: 'Location Type', required: true, type: 'dropdown', options: ['WAREHOUSE', 'DISTRIBUTION_CENTER', 'STORE', 'CUSTOMER', 'SUPPLIER', 'CARRIER', 'CROSS_DOCK', 'YARD', 'OFFICE', 'PORT', 'TERMINAL', 'OTHER'] },
  { name: 'locationSubType', label: 'Location Sub Type' },
  { name: 'description', label: 'Description', type: 'textarea' },
  { name: 'addressLine1', label: 'Address Line 1' },
  { name: 'addressLine2', label: 'Address Line 2' },
  { name: 'addressLine3', label: 'Address Line 3' },
  { name: 'city', label: 'City' },
  { name: 'state', label: 'State' },
  { name: 'stateCode', label: 'State Code' },
  { name: 'country', label: 'Country' },
  { name: 'countryCode', label: 'Country Code' },
  { name: 'postalCode', label: 'Postal Code' },
  { name: 'county', label: 'County' },
  { name: 'latitude', label: 'Latitude', type: 'number' },
  { name: 'longitude', label: 'Longitude', type: 'number' },
  { name: 'timezone', label: 'Timezone' },
  { name: 'timezoneCode', label: 'Timezone Code' },
  { name: 'contactName', label: 'Contact Name' },
  { name: 'contactPhone', label: 'Contact Phone' },
  { name: 'alternatePhone', label: 'Alternate Phone' },
  { name: 'contactEmail', label: 'Contact Email', type: 'email' },
  { name: 'faxNumber', label: 'Fax Number' },
  { name: 'operatingHours', label: 'Operating Hours' },
  { name: 'notes', label: 'Notes', type: 'textarea' },
  { name: 'active', label: 'Active', type: 'checkbox' }
];
